fixtures:
  forge_modules:
    beaver: "evenup/beaver"
    concat: "puppetlabs/concat"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "3.2.0"
    sensu: "sensu/sensu"
  symlinks:
    postfix: "#{source_dir}"
