---
  .travis.yml:
    hc_secure: "bjc3prKRyKK5HGBdJXucCCFZoT527w43db9YAj0BTvkIdJV6PH+V+bbKmQFOueCRiRtUGn4ngHumGJmm5sr5k3XUOUCTAVedXohfmTFhi/1+UeSt1QiF98H/xHfifbPhFKhtmIMnaTPw+MuWzlfPRxU+kc7HMhyPzEd2+L3fkiI="
