---
  .travis.yml:
    hc_secure: "Zu/jcqq68fmYZ9x3W+jIeIiOHZOmHKUXiB5tQ/mIFizba3W6/1UWk6j58L53\np4k9TIu7CB4EggA3ExoZ+AKw0leHAkrn9SlqCPk19Sack0TC5ZCZww4W6Jb/\ncAzFQXAxQ6aOL9HyboNTKVhg6FoGtNrWMFEWMdVSQl7c7Ul8IaU="
